---
apiVersion: v1
kind: Pod
metadata:
  name: centos
  namespace: lab-1
  labels:
    app: centos
spec:
  containers:
    - name: centos
      image: centos:7
      # Just spin & wait forever
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do curl -m5 http://lab-1.nginx-svc.cluster.local; sleep 3; done;" ]
      resources: {}